language: perl
perl:
  - "5.8.8"
  - "5.8.8-dbg"
  - "5.8.8-thr"
  - "5.8.9-thr"
  - "5.8"
  - "5.10.0"
  - "5.10.0-thr"
  - "5.10.1"
  - "5.10.1-thr"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.20"
  - "5.22"
  - "5.24"
  - "5.26"
  - "dev"
before_install:
  - eval $(curl https://travis-perl.github.io/init) --auto
branches:
  except:
    - /^wip\//
    - /^blocked/
sudo: false
notifications:
  email: false
